### ISSUE TITLE
System.InvalidOperationException: 'Could not load the embedded file manifest 

### ISSUE THREAD

**Issue by aslamy** [maikebing/SilkierQuartz#125]
Hi !

I get this exception when I run: SilkierQuartz.Example

System.InvalidOperationException: 'Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'SilkierQuartz'.'

**Comment by Peter939** [comment]
Hi, have the same problem.

**Comment by Peter939** [comment]
Hi,
The packages "Microsoft.Extensions.FileProviders.Embedded" and "Microsoft.Extensions.FileProviders.Physical"
is not in net5 and net6 targets.

**Comment by emcdng** [comment]
Hi guys,

could you solve the problem?
