### ISSUE TITLE
Are you interested in some updates?

### ISSUE THREAD

**Issue by frblondin** [maikebing/SilkierQuartz#127]
Hi there, I've just come across this repo while I was working on Quartzmin. I would like to use your project since it seems to be much more active :-). Would you be interested in the following updates if I submit PR (code is already there locally in my environment):
* New `IsReadOnlyMode` to have a readonly interface that lets you tracking the progress of jobs/triggers without having the ability to operate (e.g. start/stop/edit/...)
* Signed assembly (my project uses strong signed assemblies so I need all assemblies to be signed)
* Modernized projects to SDK format
* Update .Net from 4.5.2 to 4.8
* Update Quartz from 3.0.7 to 3.3.3

**Comment by maikebing** [comment]
Sounds very good. 
You are welcome to submit a PR

**Comment by frblondin** [comment]
Carp, I've just seen that you've removed the compatibility with OWIN. I am still using it, so I am afraid that this library won't be a good fit for my project...

Thanks anyway and looking forward to using your version in the future!
