### ISSUE TITLE
Package SilkierQuartz 5.0.178 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by lerasah** [maikebing/SilkierQuartz#52]
Just found this amazing package as the perfect alternative solution to Quartzmin to suit my need. According to what the project homepage says, I tried to install to a .net core 3.1 project and got this error.

```
PM> Install-Package SilkierQuartz
Restoring packages for E:\Repos\something.csproj...

NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

NU1701: Package 'Swashbuckle.Core 5.6.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Install-Package : NU1202: Package SilkierQuartz 5.0.178 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package SilkierQuartz 5.0.178 supports: net5.0 
(.NETCoreApp,Version=v5.0)
```

Any solution is appreciated.

**Comment by maikebing** [comment]
I tried to be compatible with Asp.Net Core 3.1, please update to 5.0.196

**Comment by lerasah** [comment]
> I tried to be compatible with Asp.Net Core 3.1, please update to 5.0.196

Installing Microsoft.Extensions.Primitives 3.1.10.
Installing Microsoft.Extensions.FileSystemGlobbing 3.1.10.
Installing Microsoft.Extensions.FileProviders.Abstractions 3.1.10.
Installing Microsoft.Extensions.FileProviders.Physical 3.1.10.
Installing Microsoft.Extensions.FileProviders.Embedded 3.1.10.
Installing JsonSubTypes 1.8.0.
Installing Handlebars.Net 1.11.5.
Installing SilkierQuartz.Plugins.RecentHistory 5.0.196.
Installing SilkierQuartz 5.0.196.
NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
NU1701: Package 'Swashbuckle.Core 5.6.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Install-Package : NU1605: Detected package downgrade: Microsoft.AspNetCore.Mvc.NewtonsoftJson from 3.1.10 to 3.1.7. Reference the package directly from the project to select a 
different version. 
 HT.WebApi -> SilkierQuartz 5.0.196 -> Microsoft.AspNetCore.Mvc.NewtonsoftJson (>= 3.1.10) 
 HT.WebApi -> Microsoft.AspNetCore.Mvc.NewtonsoftJson (>= 3.1.7)
At line:1 char:1
+ Install-Package SilkierQuartz
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'HT.WebApi'.
At line:1 char:1
+ Install-Package SilkierQuartz
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by lerasah** [comment]
> I tried to be compatible with Asp.Net Core 3.1, please update to 5.0.196

Installing Microsoft.Extensions.Primitives 3.1.10.
Installing Microsoft.Extensions.FileSystemGlobbing 3.1.10.
Installing Microsoft.Extensions.FileProviders.Abstractions 3.1.10.
Installing Microsoft.Extensions.FileProviders.Physical 3.1.10.
Installing Microsoft.Extensions.FileProviders.Embedded 3.1.10.
Installing JsonSubTypes 1.8.0.
Installing Handlebars.Net 1.11.5.
Installing SilkierQuartz.Plugins.RecentHistory 5.0.196.
Installing SilkierQuartz 5.0.196.
NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
NU1701: Package 'Swashbuckle.Core 5.6.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Install-Package : NU1605: Detected package downgrade: Microsoft.AspNetCore.Mvc.NewtonsoftJson from 3.1.10 to 3.1.7. Reference the package directly from the project to select a 
different version. 
 MyApiProject -> **SilkierQuartz 5.0.196** -> Microsoft.AspNetCore.Mvc.NewtonsoftJson (>= 3.1.10) 
 MyApiProject -> Microsoft.AspNetCore.Mvc.NewtonsoftJson (>= 3.1.7)
At line:1 char:1
+ Install-Package SilkierQuartz
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'MyApiProject'.
At line:1 char:1
+ Install-Package SilkierQuartz
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : `NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
