### ISSUE TITLE
Could SilkierQuartz tartget net standard 2.1 ?

### ISSUE THREAD

**Issue by khanhna** [maikebing/SilkierQuartz#64]
Hi guys,

I just try it out with a cluster situation and this repo perform pretty awesome, and i was really serious planning to bring this to production.

But could be it possible to support target framework net standard 2.1 ?

The reason behind this is i was come accross some of Quartz management UI repo and they was not quite actively after a while.
And i plan to upgrade my project for quite a long time.
So to ensure to break nothing, target net standard 2.1 will be pretty nice, or otherwise, moving from net5 to net6 and net6 to net8 would be painful or may be the worst case is to drop support to this one.

Thanks to bring us this awesome tool anyway :D

**Comment by maikebing** [comment]
That's a good idea!，Can you submit a PR?

**Comment by khanhna** [comment]
https://github.com/maikebing/SilkierQuartz/pull/66

Here you go bro, along with result after it work, but take the consider as i was noted in detailed there.
Happy weekend 🎉 🎉

**Comment by maikebing** [comment]
Thank you for your work. But conflicts with #65
Because
Net Standard 2.1：
public JsonResult(object value, JsonSerializerSettings serializerSettings);

Net 5.0 :
public JsonResult(object value, object serializerSettings);

**Comment by maikebing** [comment]
This issue cannot be solved. and I'm closing it now.
