### ISSUE TITLE
Could we have some simple kind of authentication ?

### ISSUE THREAD

**Issue by khanhna** [maikebing/SilkierQuartz#69]
Hi, 

Keeping working on it, and the situation come when I want some kind of secure Silkier Quartz.
The idea is passing a string to new property UserName and Password in `SilkierQuartzOptions`, and the login page would be a simple string match-up when provide authentication.
If one of the 2 property was null or empty the authentication process would not apply.

Should I add this ?

Btw, I saw in the project that we purely target .net core, so why `Target-Specific Directives` regions exists ?
Should I clean that up too ?

**Comment by maikebing** [comment]
You are welcome.

**Comment by khanhna** [comment]
@maikebing it's me again, PR was submitted to add authentication feature 🎉

**Comment by maikebing** [comment]
great job.

**Comment by khanhna** [comment]
Just a small remind, you need to update the instruction to include 3 line of `app.AddAuthentication` as well, otherwise exception will be throw
