### ISSUE TITLE
How to change the logo?

### ISSUE THREAD

**Issue by biapar** [maikebing/SilkierQuartz#72]
How to change the logo?

**Comment by khanhna** [comment]
Not sure if that possible, currently logo image is embedded resource, along with a ton of static resources, even include the handle bar views.
Even if you change the `SitePhysicalDirectory` options, and prepare replacement image, other static resources still not be found.

So in short... i don't think that possible at this point.
But still... a nice option to have.

**Comment by maikebing** [comment]
SilkierQuartzOptions

  public string Logo { get; set; } = "Content/Images/logo.png";

 Supports any value that is a viable as a img src attribute value: url, or base64
  src='data:image/jpeg;base64, LzlqLzRBQ...[end of base64 data]'
 Defaults to the SilkierQuartz original logo
