### ISSUE TITLE
Trigger job manually

### ISSUE THREAD

**Issue by sezerkorkmaz** [maikebing/SilkierQuartz#90]
when trigger job manually like  

Scheduler.TriggerJob(JobKey.Create(jobkey), job.JobDataMap);

throws exception 

Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]

there is no problem in the job's execute method. it's just console log.

**Comment by MarkusGalant** [comment]
@sezerkorkmaz 
Hi You should use Microsoft DI. The one possible working solution :
```
 services.AddSilkierQuartz(it =>
            {
                var section = Configuration.GetSection("Quart");
                foreach (var config in section.GetChildren())
                {
                    it.Add(config.Key, config.Value);
                }
            });
            services.AddQuartz(it => it.UseMicrosoftDependencyInjectionJobFactory());
            
```
